# Generated by Django 4.0.4 on 2023-02-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=20)),
                ('one_h', models.CharField(max_length=20)),
                ('twenty_four_h', models.CharField(max_length=20)),
                ('seven_d', models.CharField(max_length=20)),
                ('market_cap', models.CharField(max_length=20)),
                ('volume', models.CharField(max_length=20)),
                ('circulating_supply', models.CharField(max_length=20)),
            ],
        ),
    ]
